### ISSUE TITLE
BUG - olx crawler

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/sonub#180]
Return-Path: <sonub@x2.localdomain>
X-Original-To: sonub
Delivered-To: sonub@x2.localdomain
From: "(Cron Daemon)" <sonub@x2.localdomain>
To: sonub@x2.localdomain
Subject: Cron <sonub@x2> cd /home/sonub/www/wp-content/plugins/xapi-2/cron; /usr/bin/php cron-olx-crawler.php
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=59352>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/1002>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/sonub>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=sonub>
X-Cron-Env: <USER=sonub>
Date: Fri,  8 Sep 2017 18:55:11 +0800 (PHT)
Status: R

PHP Fatal error:  Uncaught InvalidArgumentException: Expecting a DOMNodeList or DOMNode instance, an array, a string, or null, but got "boolean". in /home/sonub/www/wp-content/plugins/xapi-2/vendor/symfony/dom-crawler/Crawler.php:123
Stack trace:
#0 /home/sonub/www/wp-content/plugins/xapi-2/vendor/symfony/dom-crawler/Crawler.php(70): Symfony\Component\DomCrawler\Crawler->add(false)
#1 /home/sonub/www/wp-content/plugins/xapi-2/cron/cron-olx-crawler.php(41): Symfony\Component\DomCrawler\Crawler->__construct(false)
#2 {main}
  thrown in /home/sonub/www/wp-content/plugins/xapi-2/vendor/symfony/dom-crawler/Crawler.php on line 123

Fatal error: Uncaught InvalidArgumentException: Expecting a DOMNodeList or DOMNode instance, an array, a string, or null, but got "boolean". in /home/sonub/www/wp-content/plugins/xapi-2/vendor/symfony/dom-crawler/Crawler.php:123
Stack trace:
#0 /home/sonub/www/wp-content/plugins/xapi-2/vendor/symfony/dom-crawler/Crawler.php(70): Symfony\Component\DomCrawler\Crawler->add(false)
#1 /home/sonub/www/wp-content/plugins/xapi-2/cron/cron-olx-crawler.php(41): Symfony\Component\DomCrawler\Crawler->__construct(false)
#2 {main}
  thrown in /home/sonub/www/wp-content/plugins/xapi-2/vendor/symfony/dom-crawler/Crawler.php on line 123

&

**Comment by thruthesky** [comment]
half fixed. it's minor error.
